STUDY_NAME:  "LGBM_optimization_Competencia01_Experimento01"

competencia01:
  DATA_PATH: "data/competencia_01_crudo.csv"
  SEMILLA:  [80021, 80039, 80051, 80071, 80077]
  MES_TRAIN: [202101, 202102,202103 ] # 202102
  MES_VALIDACION: 202104
  MES_TEST: 202106
  GANANCIA_ACIERTO: 780000
  COSTO_ESTIMULO: 20000
  FINAL_TRAIN:  [202103, 202104]  # [202101, 202102,202103,202104]
  FINAL_PREDIC: 202106
  UMBRAL: 0.025

PARAMETROS_LGB:
    n_trial: 100
    num_leaves: [8, 100]
    num_iterations: [50, 1000]
    feature_fraction: [0.1, 1.0]
    learning_rate: [0.005, 0.3]
    bagging_fraction: [0.1, 1.0]
    min_data_in_leaf: [1, 1000]

